export const departamentos = {
    "Amazonas": ["Leticia", "Puerto Nariño", "Tarapacá"],
    "Antioquia": ["Medellín", "Envigado", "Bello", "Itagüí"],
    "Arauca": ["Arauca", "Tame", "Arauquita"],
    "Atlántico": ["Barranquilla", "Soledad", "Malambo"],
    "Bolívar": ["Cartagena", "Magangué", "Mompox"],
    "Boyacá": ["Tunja", "Duitama", "Sogamoso"],
    "Caldas": ["Manizales", "Villamaría", "Chinchiná"],
    "Caquetá": ["Florencia", "San Vicente del Caguán"],
    "Casanare": ["Yopal", "Aguazul", "Hato Corozal"],
    "Cauca": ["Popayán", "Santander de Quilichao"],
    "Cesar": ["Valledupar", "La Paz", "Riohacha"],
    "Chocó": ["Quibdó", "Condoto"],
    "Córdoba": ["Montería", "Lorica", "Cereté"],
    "Cundinamarca": ["Bogotá", "Soacha", "Fusagasugá"],
    "Guainía": ["Inírida"],
    "Guaviare": ["San José del Guaviare"],
    "Huila": ["Neiva", "Pitalito", "Campoalegre"],
    "La Guajira": ["Riohacha", "Maicao", "Fonseca"],
    "Magdalena": ["Santa Marta", "Ciénaga", "Aracataca"],
    "Meta": ["Villavicencio", "Acacías", "Restrepo"],
    "Nariño": ["Pasto", "Tumaco", "Ipiales"],
    "Norte_De_Santander": ["Cúcuta", "Pamplona", "Ocaña"],
    "Putumayo": ["Mocoa", "Puerto Asís"],
    "Quindío": ["Armenia", "Montenegro", "Quimbaya"],
    "Risaralda": ["Pereira", "Dosquebradas", "La Virginia"],
    "San Andres y Providencia": ["San Andrés", "Providencia"],
    "Santander": ["Bucaramanga", "Cúcuta", "Barrancabermeja"],
    "Sucre": ["Sincelejo", "Sampués", "Corozal"],
    "Tolima": ["Ibagué", "Melgar", "Espinal"],
    "Valle Del Cauca": ["Cali", "Palmira", "Tuluá", "Buga"],
    "Vaupés": ["Mitú"],
    "Vichada": ["Puerto Carreño"]
  };
  